---
- name: Generate IOS-XE Router Configurations
  connection: local
  hosts: cisco-ios-xe-routers
  gather_facts: no
  tasks:
    - template:
        src=templates/cisco_ios_xe_router.j2
        dest=configs/{{ inventory_hostname }}
